### ISSUE TITLE
Please more wiki about this mod

### ISSUE THREAD

**Issue by StudentWeis** [glisco03/isometric-renders#10]
Today when I used this mod, I suddenly discover that the shortcut key **"C" and "shift+C"** can select the area more easily. But I can't find any hint about this in the wiki. So please more help about this mod which is wonderful. Thanks~

**Comment by Noaaan** [comment]
![image](https://user-images.githubusercontent.com/4163353/131710091-86b3a640-ae4d-42c6-ab87-43d4d9f93026.png)

**Comment by StudentWeis** [comment]
Sorry for my fault.
