### ISSUE TITLE
i dont even know

### ISSUE THREAD

**Issue by ghost** [glisco03/isometric-renders#108]
my other mods are chunky, c2me, fabric language kotlin, faster random, ferritecore, isometric renders, lithium, methane, mod menu, noisium, nvidium, sodium, xaero's world map, zoomify, and im on 1.20.1
https://github.com/user-attachments/assets/1a1151d7-cdec-41ba-a00d-969d3970770f

**Comment by ghost** [comment]
it also happens if i have no mods installed, and it also happens on three dimensional selections if they have too many blocks
![ssa](https://github.com/user-attachments/assets/29968f1b-5199-4058-94e1-b33acab15764)

**Comment by AriaElidove** [comment]
This is something which is caused by render distance. The simpliest solution? Get a mod to boost your render distance by some extreme amount. 

Me at 1000 ~ 1000, rendering from 1000 ~ 1000 to -1000 ~ 1000:
![image](https://github.com/user-attachments/assets/611c34fd-0e55-49f2-9b10-00b4a7a2e45e)

**Comment by gliscowo** [comment]
As @AriaElidove correctly described in their above comment, for what should be mostly self-explanatory reasons given that it's a client mod, Isometric Renders can only create renders of chunks which are currently visible in your render distance.

The somewhat counterintuitive rotation behavior you're seeing is a consequence of your selection being larger than the chunks that are loaded and that it can thus render - this means that there is effectively an invisible second half to the slice of world that you're rotating, causing the axis of rotation to appear off.

Feel free to ask if you have any more questions
Cheers
