### ISSUE TITLE
Ctrl F12 does not close Inventories when Exiting

### ISSUE THREAD

**Issue by AriaElidove** [glisco03/isometric-renders#109]
if you do Ctrl F12 while in an inventory and hit "escape" to get out of the UI, it will also close the Inventory's UI, but keep certain Inventories (like chests) open

**Comment by gliscowo** [comment]
Thanks for bringing this up, it has now been fixed in [0.4.8 for 1.21.2/3](https://modrinth.com/mod/M0aimenU/version/MU4TcUm3)
Cheers
