### ISSUE TITLE
Allow Transparency on Animation Exports

### ISSUE THREAD

**Issue by AriaElidove** [glisco03/isometric-renders#113]
I want my animations to have transparent bgs. Thats all

**Comment by gliscowo** [comment]
This is already possible with APNG. MP4 as a format simply does not support an alpha channel, and transparent GIFs are an absolute pain to create in any remotely usable way. As such, use APNG if you need a transparent background in your animation (it's basically an image sequence but in a single file) and process it further externally if required

Cheers
