### ISSUE TITLE
Pojavlauncher  crash

### ISSUE THREAD

**Issue by nikitadan4pi** [glisco03/isometric-renders#115]
Crash on start 
logs
[latestlog.txt](https://github.com/user-attachments/files/16961119/latestlog.txt)
Blackview Oscal C80
HolyGL4ES

**Comment by Noaaan** [comment]
Are you sure this issue was caused by Isometric Renders? Looking at the log neither it or its dependencies were loaded when the game crashed.
Looking a bit further it seems you are using JourneyMap for 1.20.4, which would be incompatible with 1.20.1

**Comment by Minenash** [comment]
Can confirm, it looks like the error is with loading JourneyMap, and that it looks like you're using the wrong version of it for your minecraft version

**Comment by nikitadan4pi** [comment]
now I tried download it again. In actions I found working on 1.20.5 version. But all builds for 1.20.4 are expired. What can I do, if I need 1.20.4?

**Comment by Noaaan** [comment]
You should just be able to use the existing 1.20.4 release: https://github.com/gliscowo/isometric-renders/releases/tag/0.4.7%2B1.20.3
