### ISSUE TITLE
Isometric Renders doesn't support the Fabric Renderer API

### ISSUE THREAD

**Issue by LambdAurora** [glisco03/isometric-renders#12]
The title explains itself mostly.

![2021-09-11_22-06](https://user-images.githubusercontent.com/12587332/132960422-5ba36292-a9b9-4fe8-b706-91e8c3cb8210.png)

As you can see on this screenshot, in world the daffodil renders in the big flower pot, but in isometric renders it doesn't render at all, the Fabric Renderer API models are entirely ignored.

**Comment by gliscowo** [comment]
I am aware of this issue however I have never gotten the chance to really look into it. To be quite honest I don't really know where to start anyways as I have no idea where Fabric injects its rendering functions. In case you have some more insight into this and could either join my discord or give me a few pointers here that'd be great, otherwise it might be a while before I look into this.

**Comment by LambdAurora** [comment]
> I am aware of this issue however I have never gotten the chance to really look into it. To be quite honest I don't really know where to start anyways as I have no idea where Fabric injects its rendering functions. In case you have some more insight into this and could either join my discord or give me a few pointers here that'd be great, otherwise it might be a while before I look into this.

One of the thing to implement is the `RenderAttachedBlockView` interface that allows to fetch some of arbitrary data from a block entity (which implements `RenderAttachmentBlockEntity`) in a thread-safe manner.

The other thing is the Fabric Renderer API introduces the `FabricBakedModel`, if `isVanillaAdapter` is true, it means it's just a Vanilla model, else there's the `emitBlockQuads` and `emitItemQuads` that can be re-implemented by mods. You might want to take a look at the `RenderContext` interface and at Indigo which is the base implementation of the API.

**Comment by gliscowo** [comment]
Implemented in [0.3.0](https://modrinth.com/mod/isometric-renders/version/F90awBdP), although currently only for Indigo
Cheers
