### ISSUE TITLE
Campfire particles do not show in area render

### ISSUE THREAD

**Issue by zedwick** [glisco03/isometric-renders#14]
The particles emitted from campfires do not show in the area render.

I tested a plain campfire which should emit `minecraft:campfire_cosy_smoke`.
I assume `minecraft:campfire_signal_smoke` also does not show, but have not tested this directly.

Tested using version 0.2.7 on MC 1.17.1.

**Comment by gliscowo** [comment]
Implemented in [0.3.0](https://modrinth.com/mod/isometric-renders/version/F90awBdP)
