### ISSUE TITLE
Fluid Displacement in Rendering

### ISSUE THREAD

**Issue by ChrysanthCow** [glisco03/isometric-renders#16]
[Crash Log](https://paste.ee/p/7bSMF)

Placing fluids has a chance to crash the game, otherwise the fluids are rendered in incorrect positions.

All tested on Isometic Renders 0.2.7

Issue tested and found on:
Fabric API 0.42.5 (1.18)
Fabric API 0.43.1 (1.18)
Fabric API 0.44.0 (1.17)

My steps to reproduce:
- Select an area with a fluid
- /isorender it
- Bug found

**Comment by MerchantPug** [comment]
This only happened first time though, I've somehow not ran into it when trying to get it for a 2nd time.

**Comment by ChrysanthCow** [comment]
![](https://i.imgur.com/aywRl8m.png)

**Comment by gliscowo** [comment]
Fixed in 0.2.11
