### ISSUE TITLE
GUI is too big

### ISSUE THREAD

**Issue by Rafii2198** [glisco03/isometric-renders#19]
I am playing on GUI x3 size (I am used to it) on 1920x1080 and the GUI of this mod is just too big with it, just look:
![obraz](https://user-images.githubusercontent.com/26695327/153061932-4b5d5d58-301e-4284-a5c5-f00a8e7a02ff.png)
I have no idea if another mod is causing it, I sadly don't have time to check now.

**Comment by gliscowo** [comment]
As much as I would like to do something about this, Minecraft's GUI system does not really allow me to go about this in another way without having to write a significant amount of new UI code. For now I'll sadly just have to tell you to turn down your GUI scale when using the render UI
Cheers

**Comment by PeakXing** [comment]
use malilib fabric

**Comment by gliscowo** [comment]
As a genuine question as I know nothing about what it does in this case, how would that help?

**Comment by gliscowo** [comment]
Given that nobody has responded to this in quite a while now, I'll go ahead and close this issue as (at least currently) it's not something I can really fix
Cheers
