### ISSUE TITLE
[Suggestion] Add lighting support to blocks/items rendering

### ISSUE THREAD

**Issue by Brandcraf06** [glisco03/isometric-renders#2]
It would be nice, and better, if the Blocks/Items/Entities rendering can have lighting support like area rendering

**Comment by glisco03** [comment]
Heya, what exactly do you mean by this? The current lighting situation is a bit weird to explain. If you would like to go in-depth on this, as there quite a few things I could probably do, I would prefer doing that via Discord

**Comment by glisco03** [comment]
Newest build has the option for non-flat lighting. If you want something else as well a system is now in place so I can add more easily. I'll close this for now
