### ISSUE TITLE
坐等大佬PR一个中文包

### ISSUE THREAD

**Issue by mouren-zhang** [glisco03/isometric-renders#21]

**Comment by pluiedev** [comment]
I'm working on it, but as most strings in the mod are _hardcoded_ (thank you @gliscowo for ignoring what I said about I18n), it'd take a while to migrate to lang files properly.

正整这活 但因为目前模组里的文字都是写死在代码里的（感谢 @gliscowo 不听劝（bushi）），要把它们都挑出来放到语言文件里要花点时间
