### ISSUE TITLE
Desperately need a way to increase the scale above 450 to like almost 1000

### ISSUE THREAD

**Issue by Funtimes909** [glisco03/isometric-renders#26]
I need this for icon making

**Comment by gliscowo** [comment]
Why exactly do you need this? Can't you simply achieve the same thing by rendering at a higher resolution than you need and cropping the image?

**Comment by Funtimes909** [comment]
I am trying to give the minecraft launcher icons customized icons, however whenever I change the file path to the png file in the launcher settings file, It always shows up as the same size unless I increase the scale of the render
Also the minecraft launcher expects 128x128 pixels

**Comment by gliscowo** [comment]
What I recommend you do here is increasing your renderer resolution to something larger, like 512x512 pixels. You can the use the image editing program of your choice to remove the outer, empty bit of the image and scale your icon down to a size of 128x128. This should allow you to easily achieve the scaling you want
Cheers
