### ISSUE TITLE
Caused by: java.lang.NoSuchFieldError: DISPATCHER

### ISSUE THREAD

**Issue by Jab125** [glisco03/isometric-renders#27]
![Screen Shot 2022-06-14 at 8 18 38 pm](https://user-images.githubusercontent.com/67534807/173554716-aff8aae3-87dd-4539-9a7a-429f0d0639cd.png)

**Comment by gliscowo** [comment]
Fixed in [0.3.0+1.19](https://modrinth.com/mod/isometric-renders/version/F90awBdP)
