### ISSUE TITLE
Division by 0 crash.

### ISSUE THREAD

**Issue by SzczurekYT** [glisco03/isometric-renders#34]
Hello
I downloaded your mod, and tried to render pufferfish. I enabled "Run Animations" and after a while (around 10 seconds I think) my game crashed with this report:
[crash-2022-07-02_10.10.55-client.txt](https://github.com/gliscowo/isometric-renders/files/9032663/crash-2022-07-02_10.10.55-client.txt)

**Comment by gliscowo** [comment]
Fixed in [0.3.1+1.18](https://modrinth.com/mod/isometric-renders/version/hrCUimJa)

**Comment by SzczurekYT** [comment]
> Fixed in [0.3.1+1.18](https://modrinth.com/mod/isometric-renders/version/hrCUimJa)

Thanks, I happened only one time to me, but still it's nice to have it fixed.
