### ISSUE TITLE
Player rendering

### ISSUE THREAD

**Issue by BuggyAl** [glisco03/isometric-renders#39]
Not sure if it is a bug or an intended feature. Either way, I want to render player models.
![Error](https://user-images.githubusercontent.com/64368488/179421618-4cb64b97-6f02-4348-a95e-99148f0e7c55.png)

**Comment by gliscowo** [comment]
This is now available in [0.4.1](https://modrinth.com/mod/isometric-renders/version/6CJfEFc0) with the separate `/isorender player` command
Cheers
