### ISSUE TITLE
how to remove area?

### ISSUE THREAD

**Issue by LFGaming** [glisco03/isometric-renders#4]
When i use my [ISO] keybind, then I see the white lines where I selected my area. But how do I remove those lines when I am finished with my render/ area?

This is what i mean:
![image](https://user-images.githubusercontent.com/38732192/124770900-0121f800-df3b-11eb-9e2f-5812d1b789b4.png)

**Comment by gliscowo** [comment]
Just in case you haven't accidentally stumbled upon it yet, you use the keybind while sneaking to clear your selection
