### ISSUE TITLE
Segmentation fault produced by only rendering air

### ISSUE THREAD

**Issue by Phoenix-Starlight** [glisco03/isometric-renders#41]
Reproduction steps:
Get into a space with air.
Issue ``/isorender area ~ ~ ~ ~ ~ ~`` or select a box full of air only.
It will crash.
[hs_err_pid11558.log](https://github.com/gliscowo/isometric-renders/files/9184925/hs_err_pid11558.log)
Error that appears before it seg faults.
``[14:47:25] [Render thread/INFO]: OpenGL debug message: id=1, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION in glBufferData(no buffer bound)'
``

**Comment by gliscowo** [comment]
What version of the mod, what version of Minecraft, what version of the dependencies... Basically what I'm saying is please include your log

**Comment by Phoenix-Starlight** [comment]
Oh. ok.
[2022-07-25-4.log](https://github.com/gliscowo/isometric-renders/files/9185775/2022-07-25-4.log)

**Comment by gliscowo** [comment]
Thanks for reporting this, it's now fixed in version [0.3.2+1.18](https://modrinth.com/mod/isometric-renders/version/0.3.2%2B1.18)
Cheers
