### ISSUE TITLE
Does not work on MacOS

### ISSUE THREAD

**Issue by LemmaEOF** [glisco03/isometric-renders#42]
Isometric Renders [forcibly initializes AWT](https://github.com/gliscowo/isometric-renders/blob/1.19/src/main/java/com/glisco/isometricrenders/mixin/IsometricMixinPlugin.java#L16-L18), which causes the game to never launch on MacOS. AWT is incompatible with LWJGL on Mac due to Mac's rendering constraints. An alternative method for copying images would be necessary. I know this is meant to be a Mac workaround, but it does result in the game hanging as soon as the window tries to open.

**Comment by LemmaEOF** [comment]
Oh, it looks like there's a command-line arg for disabling it? I'll give that a look. Might be nice to have that documented.

**Comment by Noaaan** [comment]
This should be fixed in 1.19, but it is not backported for the 1.18.2 builds.
You can however use the `isometric-renders.disableClipboard` [system property](https://stackoverflow.com/questions/7054972/java-system-properties-and-environment-variables/7054981#7054981) to disable it.

**Comment by Noaaan** [comment]
Is it still present in 1.19?

**Comment by LemmaEOF** [comment]
oh right yeah this is a 1.18.2 instance I literally forgot lmao

never file issues while tired folks
