### ISSUE TITLE
Toggle corner block rendering

### ISSUE THREAD

**Issue by erxson** [glisco03/isometric-renders#43]
Just not render corner two blocks instead of breaking them before render

**Comment by BasiqueEvangelist** [comment]
Поясни, пожалуйста (можно на русском), а то ничего не понятно.

**Comment by erxson** [comment]
К примеру, чтобы сделать ровное выделение территории, я ставлю два угловых блока и с помощью f3 узнаю их координаты и всписываю в команду /isorender. Но чтобы они не попадали в рендереное изображение, эти угловые блоки нужно сломать, а когда перерендриваешь по новой, то приходится их снова ставить и убирать. А галочка "Ignore corner blocks" будет игнорировать эти угловые блоки при рендере.

**Comment by Jetsparrow** [comment]
> For example, to make a precise selection of the territory, I put two corner blocks and with the help of f3 I find out their coordinates and write them into the /isorender command. But in order for them not show up in the rendered image, these corner blocks need to be removed, and when you render a new image you have to place and remove them again. A "Ignore corner blocks" checkbox will ignore these blocks when rendering.

Won't you need two checkboxes then - one for each corner? You might want to render one, but not the other.

Разве тогда потребуются не две галочки - по одной на угол? Может одинблок рендерить надо, а второй нет.

**Comment by gliscowo** [comment]
I personally don't regard such a feature as necessary given that you can simply use the `[ISO] Select Area` hotkey instead. It allows you to visually select an area of the world and render it with `/isorender area`, without requiring any corner blocks. Even if you wanted to mark the corners, you could place the blocks just outside the box and press the hotkey with sufficient distance to select the air in front of it. As such, I'll close this issue for now
Cheers

**Comment by erxson** [comment]
thanks
