### ISSUE TITLE
chests not rendered

### ISSUE THREAD

**Issue by LFGaming** [glisco03/isometric-renders#5]
Chests don't render in my screenshots, is there any reason why? and or can i activate it somewhere?

**Comment by Porktuga** [comment]
glisco is working on block + entity support, chests will be able to be rendered properly soon. For now you can use [Enhanced Block Entities mod](https://modrinth.com/mod/ebe)

**Comment by gliscowo** [comment]
Implemented in [0.3.0](https://modrinth.com/mod/isometric-renders/version/F90awBdP)
