### ISSUE TITLE
Sound cuts on and off periodically when you are in the Isorender menu

### ISSUE THREAD

**Issue by EGOIST1372** [glisco03/isometric-renders#53]
Sound cuts on and off periodically when you are in the Isorender menu
even tho there is no task or render at all it still has bugged sound
I tested it beside my campfire and it was annoying
hope it get fix soon
thanks in advance <3

**Comment by gliscowo** [comment]
Thanks for bringing my attention to this, it's now been fixed in [0.4.3](https://modrinth.com/mod/isometric-renders/version/qEpYav6Y)
Cheers
