### ISSUE TITLE
[Suggestion] Export to OBJ (or any 3D Format)

### ISSUE THREAD

**Issue by GravityCY** [glisco03/isometric-renders#58]
It'd be actually really cool to be able to export to a 3d file format whether it be OBJ (or more options) or whatever is the standard.

**Comment by gliscowo** [comment]
While this would certainly be useful functionality, I currently consider it out-of-scope for Isometric - especially since there are other tools that already do this. This doesn't mean it will never be added, but not in the foreseeable future

Cheers
