### ISSUE TITLE
Tooltips render at the wrong position after attempting to render a tooltip

### ISSUE THREAD

**Issue by RyanCR03** [glisco03/isometric-renders#61]
after using /isorender tooltip, hovering over an item will make the tooltip centered to the mouse cursor instead of appearing on the side.

**Comment by gliscowo** [comment]
You'll need to give more context on this issue, as I'm not able to reproduce this. Specifically I need, at the very least, your `latest.log` from a run of the game where this problem occured, along with a minimal modlist this can be reproduced with

Cheers
