### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by mshailz** [glisco03/isometric-renders#65]
Hello, I was wondering if the mod can be updated to Modrinth as on github it's already 1.19.4? It's easier for myself and others to keep track. Thanks!

**Comment by gliscowo** [comment]
Even though Modrinth does not display it directly on the front page, a 1.19.4 version is [well-available](https://modrinth.com/mod/isometric-renders/version/0.4.4+1.19.4) and has been ever since it was made

Cheers
