### ISSUE TITLE
Preview not showing when VoxelMap is installed

### ISSUE THREAD

**Issue by CommandLeo** [glisco03/isometric-renders#69]
When [VoxelMap](https://modrinth.com/mod/voxelmap-updated) is installed together with Isometric Renders, the render preview doesn't show anything. However, exporting the render does work properly.

# How to reproduce
- Create a 1.20.1 instance with only Fabric API, owo-lib, Isometric Renders and Voxelmap installed
- Load the game and enter a world
- Run the `/isorender block stone` command, or any other rendering command of the mod

**Comment by lerokko** [comment]
I have not tested the isorenders but I can confirm that the worldmap (not the minimap) of voxelmap also just shows black when installed. I still get a lag spike so something is loaded its just rendered as black including the letterboxed dirt background at the top and bottom.

**Comment by gliscowo** [comment]
In order to even get started debugging this, I need a `latest.log` from a run of the game where this problem occured. Please upload one either here, or on https://mclo.gs

Cheers

**Comment by CommandLeo** [comment]
The logs don't include anything meaningful, otherwise I would have included them.
The issue contains the exact reproduction steps, and I've just verified that the problem occurs even with the most recent versions of all the mods installed (Fabric API 0.87.0, Isometric Renders 0.4.5, oωo 0.11.1 and VoxelMap-Updated 1.12.13).

**Comment by CommandLeo** [comment]
An update on this: this bug appears to be fixed in the latest versions of Isometric Renders and VoxelMap for 1.20.2.

However a new compatibility issue got introduced: while on the preview screen a seemingly random text appears in the scene, although it's not rendered when exporting (see the screenshot). It appears to be a UI element, as it isn't visible while F1 is toggled on. This happens only when VoxelMap is present.

![2023-10-28_18 04 37](https://github.com/gliscowo/isometric-renders/assets/51045936/14baf4ed-f334-4c1f-bdee-e7b2d50c8f2c)

# Reproduction Steps
- Create a 1.20.2 instance with Fabric and install the following mods:
  - Fabric API 0.90.4
  - oωo 0.11.3
  - Isometric Renders 0.4.5
  - VoxelMap-Updated 1.12.15
- Load the game and enter in a world
- Run the command `/isorender block barrier` (barrier is used so it's easy to see the text)
- Set the Rotation to 0 and the Slant to 0
- Observe the text on the screen
- Click the Export button
- Notice how the text wasn't rendered

**Comment by gliscowo** [comment]
Unfortunately, given that VoxelMap appears to be closed-source, I do not really have any options for investigating this problem further than simply confirming it exists. As such, I recommend you open an issue report with the maintainers of that mod instead to see if they can figure out what's going on

Cheers
