### ISSUE TITLE
Area render not working with Iris

### ISSUE THREAD

**Issue by somebirby** [glisco03/isometric-renders#7]
Rendering an area, via manual or hotkey selection, gives out an empty preview, as well as an empty fully transparent image.
The selection outline also doesn't show up.
I've guessed it was a mod incompatibility, and after removing everything but Isometric Renders, it works again.

After some testing, it would seems when playing with Iris, [the early stage shader mod](https://github.com/IrisShaders/Iris), area renders completely break (shader activated or not).

It's not problem to me, just thought I'd let it be known, so you can close this whenever.
Thanks for the great work!

**Comment by gliscowo** [comment]
As Iris completely replaces the rendering pipeline, this isn't unexpected. There's not really anything I can do apart from implement compatibility for every single alternate pipeline our there, which would be out of scope. Canvas also causes problems so I'll just say to remove these mods when using Isorenders
