### ISSUE TITLE
[bug] Isometric prevents sodiums settings ui from rendering properly ingame

### ISSUE THREAD

**Issue by EnderMelody** [glisco03/isometric-renders#70]
minecraft :1.20.1
fabric: 0.14.21
Isometric: 0.4.4
sodium: 0.4.10+build.27
having this mod installed causes the sodium settings ui to not render properly only while in a world. it is still usable but very difficult.
![image](https://github.com/gliscowo/isometric-renders/assets/12649140/ca6a1001-4d3a-4ba9-b215-c13771348547)

**Comment by Noaaan** [comment]
Duplicate of https://github.com/wisp-forest/owo-lib/issues/142. Already fixed and will be available in a future release of owo-lib
