### ISSUE TITLE
Loom Icons Missing

### ISSUE THREAD

**Issue by sheepy676** [glisco03/isometric-renders#72]
Icons for banner patterns don't render.
Steps to reproduce:
use a loom with a banner and dye of choice.

I am using the Quilt version of this mod thus I don't know if this happens on The Fabric version.

**Comment by gliscowo** [comment]
Can you illustrate (ideally with a screenshot and your `latestl.log`) what problem exactly you're after? I haven't been able to reproduce anything similar during my testing

Cheers

**Comment by gliscowo** [comment]
Since this issue has now been stale for many months, I'll go ahead and close it. Should the problem persist with the latest releases, please go ahead and reopen it

Cheers
