### ISSUE TITLE
isorender glitches sodium menu in 1.20.1

### ISSUE THREAD

**Issue by Pietr06** [glisco03/isometric-renders#73]
it seams very strange to me, but isorender appears to be the problem
without iso:
![image](https://github.com/gliscowo/isometric-renders/assets/88508843/b57c08ef-0655-47d8-8814-4d65a5bf1cf2)

with  iso:
![image](https://github.com/gliscowo/isometric-renders/assets/88508843/21d22886-12cd-4abd-8f08-b9a7312339f2)

[latest.log](https://github.com/gliscowo/isometric-renders/files/12148379/latest.log)

**Comment by Noaaan** [comment]
Duplicate of https://github.com/gliscowo/isometric-renders/issues/70

**Comment by Pietr06** [comment]
alr
