### ISSUE TITLE
Black font when exporting animations

### ISSUE THREAD

**Issue by P4ncake4451** [glisco03/isometric-renders#74]
When you export a animation with ffmpeg for example a block spinning the ui font gets black and it stays like this until you restart the game

Edit: Somehow this is a problem what only occurs while having shaders enabled. When I have shaders off the font is normal

**Comment by gliscowo** [comment]
Given that this only happen with shaders enabled and the fact that Isometric is fundamentally incompatible with shaders anyway, I'll be closing this issue. If you want to make renders with Isometric, simply disable shaders for the duration of what you're doing

Cheers
