### ISSUE TITLE
[Possibly unfixable issue] Crash when rendering Cobblemons

### ISSUE THREAD

**Issue by moninformateur** [glisco03/isometric-renders#80]
The entity renderer is unable to render Cobblemons, probably because the Cobblemon species is determined by NBT un der the cobblemon:pokemon entity. 

Could Isometric-renders be able to render the Cobblemons?

**Comment by gliscowo** [comment]
In order to debug this properly, I need your `latest.log` (or well, the log from a run of the game where this issue occured). I'm fairly confident this should be resolvable, but only the log will tell

Cheers

**Comment by moninformateur** [comment]
Seems this was fixed on my end as it doesn't crash anymore.
