### ISSUE TITLE
Incompatibility with ModernFix mod

### ISSUE THREAD

**Issue by tunaflsh** [glisco03/isometric-renders#82]
When running `/isorender area` and waiting some time inside the GUI, game crashes.

[latest.log](https://github.com/gliscowo/isometric-renders/files/13110697/latest.log)
[hs_err_pid58640.log](https://github.com/gliscowo/isometric-renders/files/13110694/hs_err_pid58640.log)

**Comment by embeddedt** [comment]
@gliscowo Does Isometric Renders do anything special with regards to freeing buffer builders? The crash appears to be caused by my [buffer builder leak workaround](https://github.com/embeddedt/ModernFix/blob/1.18/common/src/main/java/org/embeddedt/modernfix/common/mixin/bugfix/buffer_builder_leak/BufferBuilderMixin.java)

@tunaflsh Try setting `mixin.bugfix.buffer_builder_leak=false` in the ModernFix config and see if the crash is resolved.

**Comment by BasiqueEvangelist** [comment]
> @‍gliscоwo Does Isometric Renders do anything special with regards to freeing buffer builders? The crash appears to be caused by my [buffer builder leak workaround](https://github.com/embeddedt/ModernFix/blob/1.18/common/src/main/java/org/embeddedt/modernfix/common/mixin/bugfix/buffer_builder_leak/BufferBuilderMixin.java)

https://github.com/gliscowo/worldmesher/blob/1.20/src/main/java/io/wispforest/worldmesher/WorldMesh.java#L395-L397

**Comment by embeddedt** [comment]
This is problematic, as it does not set the buffer reference to `null` after freeing it, so my fix does not know to skip freeing the buffer itself.

**Comment by gliscowo** [comment]
I've published a new WorldMesher build which clears the buffer reference - an update for Isometric should follow in the coming days

Cheers

**Comment by embeddedt** [comment]
Thanks!

**Comment by gliscowo** [comment]
Well that one sadly ended up taking a whole lot longer than I planned, but I finally got around to actually doing it. [0.4.6](https://modrinth.com/mod/M0aimenU/version/S0dUbuBm) now has the new WorldMesher version in it - which should fix the problem

Cheers

**Comment by Xplodin** [comment]
seems broken still on 1.20.1. The 0.4.6 build will not load on my instance and complains about 1.20.2 being needed despite it showing 1.20.1 on CF
![image](https://github.com/gliscowo/isometric-renders/assets/13007677/4e517d89-137c-430b-9be2-19eb3682db40)


Maybe an oversight idk. Trying the modernfix config change now
