### ISSUE TITLE
Doesn't seem to be compatible with optifine and/or optifabric

### ISSUE THREAD

**Issue by RandomGgames** [glisco03/isometric-renders#9]

**Comment by gliscowo** [comment]
This is a known problem caused by one of Optifine's transformations. I can't do anything about it and will just recommend you either remove Optifine temporarily when you need isorenders or just switch to Iris, Sodium or Canvas outright

**Comment by DearFox** [comment]
It's a shame that it's not compatible with optifine. This mod would have helped me a lot with documentation for the CIT resource pack.
