### ISSUE TITLE
Is there any setting to change the layout of the UI interface?

### ISSUE THREAD

**Issue by Utopia1916** [glisco03/isometric-renders#96]
I remember in a previous version, the rendering of buildings was centered, but now I see it's on the left side (I'm using Fabric, in version 1.20.4). 
I want it to be in the center of the screen, so I tried to find any settings to change it, but I couldn't find any, including on the wiki. Is this not something that can be changed? Can anyone tell me?

**Comment by gliscowo** [comment]
The UI switches layout depending on how much horizontal space is available in your game window. To this end, you have two options: 
- get an ultrawide monitor (I hope you realize my sarcasm)
- lower your GUI scale

Usually, the UI switches to the old 2-column layout at GUI scale 2 and below. Hope this helps!
Cheers

**Comment by Utopia1916** [comment]
holy shit ,I didn't realize it was soooooo simple
